### ISSUE TITLE
Alist network disk direct link mp3 audio file,It is not supported

### ISSUE THREAD

**Issue by JiangLongLiu** [usoonees/logseq-plugin-whisper-subtitles#11]
![image](https://github.com/user-attachments/assets/bd63ac90-0f59-4a61-ad5f-0ed32209b8d7)

```
{{renderer :media, https://abcd.com/123.mp3}}

![placeholder](https://abcd.com/123.mp3)
```

**Comment by usoonees** [comment]
Sorry, if it's not from YouTube, you'll need to download the file manually.
