### ISSUE TITLE
For local video: not supported source yet

### ISSUE THREAD

**Issue by FelixHuoEZ** [usoonees/logseq-plugin-whisper-subtitles#7]
OS: Win10
logseq version: 0.10.5
local asset: `[[../assets/费曼_镜像_镜子_前后_左右_1706374688784_0.mp4][费曼 镜像 镜子 前后 左右.mp4]]`

The message of logseq: 
![image](https://github.com/usoonees/logseq-plugin-whisper-subtitles/assets/13887263/d8b4cc68-f4c1-4167-b4c5-c807bb22c907)

**Comment by usoonees** [comment]
I am using this format for local video: `![output.mp4](../assets/output_1706446904946_0.mp4)`

```
![placeholder](filepath)
```

**Comment by FelixHuoEZ** [comment]
> I am using this format for local video: `![output.mp4](../assets/output_1706446904946_0.mp4)`我正在将这种格式用于本地视频：`![output.mp4](../assets/output_1706446904946_0.mp4)`
> 
> ```
> ![placeholder](filepath)
> ```

Sorry, I didn't mention it earlier. I am using orgmode.

**Comment by usoonees** [comment]
The issue should be resolved now. Please pull the latest code from the `logseq-whisper-subtitles-server` repository.
