### ISSUE TITLE
Transcribe native logseq audio recordings

### ISSUE THREAD

**Issue by maholli** [usoonees/logseq-plugin-whisper-subtitles#8]
Would be great if this could transcribe the native logseq voice recordings (.aac format). I get an unsupported source error at the moment. Not sure if whisper supports aac or if ffmpeg will need to re-encode. 

Thanks for the great work!

**Comment by usoonees** [comment]
Could you provide me with an example? The following format functions correctly for me:
```
![sample4.aac](../assets/sample4_1707289595664_0.aac)
```

**Comment by maholli** [comment]
ah! it was a permission issue on my end. Thanks.
