### ISSUE TITLE
age restricted video support

### ISSUE THREAD

**Issue by FelixHuoEZ** [usoonees/logseq-plugin-whisper-subtitles#9]
Hi, Is it possible to support age-restricted videos?
Currently, the age-restricted videos give the prompt:
```
logseq-whisper-subtitle-server error: 8S_wP7aHl9A is age restricted, and can't be accessed without logging in.
```

**Comment by usoonees** [comment]
Ah, it seems that's a constraint within the `pytube` library. You can try manually downloading the video through the Downie app and then utilizing the local file in logseq instead.

**Comment by FelixHuoEZ** [comment]
> Ah, it seems that's a constraint within the `pytube` library. You can try manually downloading the video through the Downie app and then utilizing the local file in logseq instead.

After download the video, I have to add the video file into the Logseq Library. It will make my graph large. I wanna know if it can extract subtitle from a video file outside.

**Comment by usoonees** [comment]
You can try to use an absolute path for extracting subtitles, such as 
```
![out](/Users/username/Downloads/out.mp4)
```
